### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by jarble** [Rerumu/Wasynth#6]
The README doesn't explain how to install this package. Are there any instructions for installation here?

**Comment by Dionysusnu** [comment]
Try `cargo install --git https://github.com/Rerumu/Wasynth`. This is usually the way to install the latest versions of rust projects from GitHub if they're designed to be a command-line tool.

**Comment by Rerumu** [comment]
We now have installation instructions here:
https://github.com/Rerumu/Wasynth/wiki/Installation
